### ISSUE TITLE
Doesnot generator changelog

### ISSUE THREAD

**Issue by MiteshShah** [skywinder/github-changelog-generator#235]
```
╭─mitesh at RestrictedArea in ~/Github/easyengine on master✔ using 15-05-14 - 12:37:53 
╰─○ github_changelog_generator                                                    
Detected user:rtCamp, project:easyengine
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :dateformat=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :include_labels=>["bug", "enhancement"],
 :exclude_labels=>["duplicate", "question", "invalid", "wontfix"],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :branch=>"origin",
 :user=>"rtCamp",
 :project=>"easyengine"}

/var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator/fetcher.rb:46:in `fetch_github_token': private method `warn' called for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator/fetcher.rb:19:in `initialize'
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator.rb:28:in `new'
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator.rb:28:in `initialize'
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/bin/github_changelog_generator:4:in `new'
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/local/bin/github_changelog_generator:23:in `load'
	from /usr/local/bin/github_changelog_generator:23:in `<main>'
```

**Comment by skywinder** [comment]
Ok, thanks! I will fix it. As workaround: please, add github token to your env or specify it by `-t` option - it will solve this bug.

**Comment by skywinder** [comment]
@MiteshShah It's strange: seems that `colorize` is not installed, thats why it crashes. 
But it's in projects dependencies. Please check if colorize is installed and let me know, if you still have this problem. (just run `gem install github_changelog_generator` and it should install it if it's not installed yet)

**Comment by MiteshShah** [comment]
@skywinder 

```
╭─mitesh at RestrictedArea in ~/Github/easyengine on master✔ using 15-05-14 - 18:25:30 
╰─○ gem install github_changelog_generator
Fetching: github_changelog_generator-1.4.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
```

```
╭─mitesh at RestrictedArea in ~/Github/easyengine on master✔ using 15-05-14 - 18:26:02 
╰─○ sudo gem install github_changelog_generator
[sudo] password for mitesh: 
Successfully installed github_changelog_generator-1.4.0
1 gem installed
Installing ri documentation for github_changelog_generator-1.4.0...
Installing RDoc documentation for github_changelog_generator-1.4.0...
```
```
╭─mitesh at RestrictedArea in ~/Github/easyengine on master✔ using 15-05-14 - 18:26:27 
╰─○ github_changelog_generator
Detected user:rtCamp, project:easyengine
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :dateformat=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :include_labels=>["bug", "enhancement"],
 :exclude_labels=>["duplicate", "question", "invalid", "wontfix"],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :branch=>"origin",
 :user=>"rtCamp",
 :project=>"easyengine"}

/var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator/fetcher.rb:46:in `fetch_github_token': private method `warn' called for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator/fetcher.rb:19:in `initialize'
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator.rb:28:in `new'
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/lib/github_changelog_generator.rb:28:in `initialize'
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/bin/github_changelog_generator:4:in `new'
	from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.4.0/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/local/bin/github_changelog_generator:23:in `load'
	from /usr/local/bin/github_changelog_generator:23:in `<main>'
```
```
github_changelog_generator -t #\!M1t3sh\H3t@l
Detected user:rtCamp, project:easyengine
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :dateformat=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :include_labels=>["bug", "enhancement"],
 :exclude_labels=>["duplicate", "question", "invalid", "wontfix"],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :branch=>"origin",
 :token=>"#!GITHUBPASSWORD",
 :user=>"rtCamp",
 :project=>"easyengine"}

Warning: GitHub API rate limit (5000 per hour) exceeded, change log may be missing some issues. You can limit the number of issues fetched using the `--max-issues NUM` argument.
Warning: GitHub API rate limit (5000 per hour) exceeded, change log may be missing some issues. You can limit the number of issues fetched using the `--max-issues NUM` argument.
Received issues: 0                              
Warning: GitHub API rate limit (5000 per hour) exceeded, change log may be missing some issues. You can limit the number of issues fetched using the `--max-issues NUM` argument.
Fetching merged dates: Done!                       
Filtered pull requests: 0
Filtered issues: 0
Fetching events for issues and PR: 0 Done!                  
Fetching closed dates for issues: Done!
Fetching tags dates: 0 Done!     
Sorting tags...
Generating log...
Done!
Generated log placed in /home/mitesh/Github/easyengine/CHANGELOG.md
```
```
╭─mitesh at RestrictedArea in ~/Github/easyengine on master✘✘✘ using 15-05-14 - 18:27:38 
╰─○ cat CHANGELOG.md 
# Change Log



\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*%  
```

**Comment by skywinder** [comment]
@MiteshShah Very interesting! Almost the same string in other part of code is not crashes.
Have no idea, what cause the problem yet. But will try to figure out with that. Thanks!

bdw: about token - it seems, that you specify wrong token - that's why it's not woork.
and shows  message:
>Warning: GitHub API rate limit (5000 per hour) exceeded, change log may be missing some issues. You can limit the number of issues fetched using the `--max-issues NUM` argument. 

fyi: you should place there 16-digit token, generated there: https://github.com/settings/tokens , not your password.

**Comment by MiteshShah** [comment]
@skywinder After given 16-digit token its working fine :)

Thanks
