### ISSUE TITLE
--unreleased-only broken

### ISSUE THREAD

**Issue by zbeekman** [skywinder/github-changelog-generator#250]
`github_changelog_generator —unreleased-only jacobwilliams/json-fortran` results in the following error:

```
/usr/local/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.6.1/lib/github_changelog_generator/generator/generator_generation.rb:14:in `compound_changelog': undefined local variable or method `all_tags' for #<GitHubChangelogGenerator::Generator:0x007f8a52072ae0> (NameError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.6.1/lib/github_changelog_generator.rb:28:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.6.1/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/local/bin/github_changelog_generator:23:in `load'
	from /usr/local/bin/github_changelog_generator:23:in `<main>’
```

**Comment by skywinder** [comment]
Thank you! Fixed in `1.6.2`
