### ISSUE TITLE
failure when creating changelog from a repo in an orginazation: can't convert Github::ResponseWrapper to Array

### ISSUE THREAD

**Issue by obihann** [skywinder/github-changelog-generator#253]
```
github_changelog_generator
Detected user:obihann-learning, project:functional-programming
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :git_remote=>"origin",
 :user=>"obihann-learning",
 :project=>"functional-programming"}

/Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator/fetcher.rb:74:in `concat': can't convert Github::ResponseWrapper to Array (Github::ResponseWrapper#to_ary gives NilClass) (TypeError)
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator/fetcher.rb:74:in `block in github_fetch_tags'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_api-0.12.3/lib/github_api/pagination.rb:37:in `each_page'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator/fetcher.rb:71:in `github_fetch_tags'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator/fetcher.rb:46:in `block in get_all_tags'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator/fetcher.rb:53:in `check_github_response'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator/fetcher.rb:46:in `get_all_tags'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/lib/github_changelog_generator.rb:28:in `run'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/gems/github_changelog_generator-1.7.0/bin/github_changelog_generator:4:in `<top (required)>'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/bin/github_changelog_generator:23:in `load'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/bin/github_changelog_generator:23:in `<main>'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
    from /Users/jhann/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by skywinder** [comment]
Hi! I figure out! It's because your repo `obihann-learning/functional-programming`  moved to another owner: `learn-something-new/functional-programming`

I will fix this later. as workaound you can do one of this things:

1. delete old remote, that references to obihann-learning/functional-programming and add learn-something-new/functional-programming instead

2. declare explicit repo name and project name in command line.

**Comment by obihann** [comment]
Wow, that explains so much. Thanks!

**Comment by perlun** [comment]
I think this can be closed. Happened to me now also when the repo had been renamed.

**Comment by nunofgs** [comment]
Just got bit by this as well. Glad I found this issue!

**Comment by Lucashuang0802** [comment]
@skywinder Agree with @perlun. This is a rare case and it is not worthy of putting resources on it. Keeping it as a reference is good enough. 😃

**Comment by olleolleolle** [comment]
Thanks, Lucas for bringing this up. Closing.

**Comment by ferrarimarco** [comment]
@olleolleolle I had the very same issue. Could be worth in presenting a meaningful error message? Thanks

**Comment by olleolleolle** [comment]
@ferrarimarco Sorry, no, the upcoming development is done using OctoKit, not github_api.

`github_api-0.12.3` was what I saw in the stackteace above.

**Comment by ferrarimarco** [comment]
You're right, here is my stacktrace:

```
/usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator/fetcher.rb:74:in `concat': can't convert Github::ResponseWrapper to Array (Github::ResponseWrapper#to_ary gives NilClass) (TypeError)
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator/fetcher.rb:74:in `block in github_fetch_tags'
	from /usr/local/bundle/gems/github_api-0.13.1/lib/github_api/pagination.rb:37:in `each_page'
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator/fetcher.rb:71:in `github_fetch_tags'
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator/fetcher.rb:46:in `block in get_all_tags'
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator/fetcher.rb:53:in `check_github_response'
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator/fetcher.rb:46:in `get_all_tags'
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/lib/github_changelog_generator.rb:29:in `run'
	from /usr/local/bundle/gems/github_changelog_generator-1.11.6/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/local/bundle/bin/github_changelog_generator:22:in `load'
	from /usr/local/bundle/bin/github_changelog_generator:22:in `<main>'

```
