### ISSUE TITLE
First time running github-changelog-generator endup in error.

### ISSUE THREAD

**Issue by muralidcis** [skywinder/github-changelog-generator#308]
Iam pretty new to this environment and Iam just trying to use your log-generater, your README, or the document says,  gem install github_changelog_generator and  go to the git repository and run github_changelog_generator -u skywinder -p ActionSheetPicker-3.0

1) Every time when i generate should i use only the skywinder credentials ? cos when i try with my own gituser name and password it says invalid credentials.

github_changelog_generator -u myusername -p password -t thenameofthetag

2) Even when i run like this on my git-repo github_changelog_generator -u skywinder -p ActionSheetPicker-3.0 i end up with the following error.

warning: Can't finish operation: GitHub API rate limit exceeded, change log may be missing some issues. You can limit the number of issues fetched using the `--max-issues NUM` argument.

/var/lib/gems/1.9.1/gems/github_changelog_generator-1.9.0/lib/github_changelog_generator/fetcher.rb:202:in `fetch_date_of_tag': undefined method `[]' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.9.0/lib/github_changelog_generator/generator/generator_tags.rb:29:in `get_time_of_tag'
    from /var/lib/gems/1.9.1/gems/github_changelog_generator-1.9.0/lib/github_changelog_generator/generator/generator_fetcher.rb:24:in `block (2 levels) in fetch_tags_dates'

OS: Ubuntu 14.4
git version 2.6.3
gem:1.8.23

kindly help me out.

**Comment by muralidcis** [comment]
sorry, it was straight forward,  

github_changelog_generator -u myusername -p repo -t thenegeratedtoken
