### ISSUE TITLE
between-tags and exclude-tags do not work in .github_changelog_generator

### ISSUE THREAD

**Issue by crucialfelix** [skywinder/github-changelog-generator#317]
When passed in as command line options they work, but not if they are in the .github_changelog_generator file:

```
exclude-tags=3.3,3.4branchpoint,3.6-branch-point,Version-3.2rc1,Version-3.2rc3,Version-3.2rc5,Version-3.2rc6,Version-3.4alpha,Version-3.4rc1,Version-3.5beta1,Version-3.5beta2,Version-3.5beta3,Version-3.5beta4,Version-3.5rc1,Version-3.5rc2,Version-3.5rc3,Version-3.6alpha1,Version-3.6alpha2,Version-3.6alpha3,Version-3.6beta1,Version-3.6beta2,Version-3.6beta3,Version-3.7.0-alpha0,Version-3.7.0-alpha1,after-qt5,before-gui-redirects-removed,before-linux,before-linux-B,before-linux-C,before-qt5,gui-redirects-removed,initial-deploy,initial-deploy-2,pre-gui-review,pre-linux-1-0,release-3.1,start,travis-temp,travis-test
```

```
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :base=>"HISTORY.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :git_remote=>"origin",
 :user=>"supercollider",
 :project=>"supercollider",
 :future_release=>"3.7.0",
 :enhancement_label=>"\"**Enhancements**\"",
 :exclude_tags=>
  "3.3,3.4branchpoint,3.6-branch-point,Version-3.2rc1,Version-3.2rc3,Version-3.2rc5,Version-3.2rc6,Version-3.4alpha,Version-3.4rc1,Version-3.5beta1,Version-3.5beta2,Version-3.5beta3,Version-3.5beta4,Version-3.5rc1,Version-3.5rc2,Version-3.5rc3,Version-3.6alpha1,Version-3.6alpha2,Version-3.6alpha3,Version-3.6beta1,Version-3.6beta2,Version-3.6beta3,Version-3.7.0-alpha0,Version-3.7.0-alpha1,after-qt5,before-gui-redirects-removed,before-linux,before-linux-B,before-linux-C,before-qt5,gui-redirects-removed,initial-deploy,initial-deploy-2,pre-gui-review,pre-linux-1-0,release-3.1,start,travis-temp,travis-test",
 :token=>"hidden value"}

Found 74 tags
/Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:155:in `filter_exact_tags': undefined method `each' for #<String:0x007fb2ac5368d8> (NoMethodError)
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:145:in `apply_exclude_tags'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:136:in `filter_excluded_tags'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:72:in `get_filtered_tags'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator.rb:29:in `run'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.10.1/bin/github_changelog_generator:4:in `<top (required)>'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/github_changelog_generator:23:in `load'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/github_changelog_generator:23:in `<main>'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by skywinder** [comment]
Related with #278
CC @dlanileonardo

**Comment by crucialfelix** [comment]
fixed
