### ISSUE TITLE
detect_since_tag undefined

### ISSUE THREAD

**Issue by wwayne** [skywinder/github-changelog-generator#328]
First thank you for this great tool, it's really useful.
I'm not familiar with ruby, so could you help me to check this problem when I execute `$ github_changelog_generator` in my project folder:
```
Found 13 tags
/Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:61:in `detect_since_tag': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:79:in `filter_since_tag'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:70:in `get_filtered_tags'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.1/lib/github_changelog_generator.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.1/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/bin/github_changelog_generator:23:in `load'
	from /usr/bin/github_changelog_generator:23:in `<main>'
```
Thank you.

**Comment by skywinder** [comment]
Hello. Can you show full command line, that you are execute?

**Comment by wwayne** [comment]
I just follow the steps in README and execute
```
$ github_changelog_generator
```
in my project root folder

**Comment by skywinder** [comment]
Ok, I will have a look for it. Can you specify, for which project are you
run this option? Is it open source?

**Comment by wwayne** [comment]
Yes,I use this for my personal open-source project : https://github.com/wwayne/react-tooltip.
I can add you as collaborator if that can help you to detect the problem.
And more info, I'm using:
* ruby 2.0.0p645
* gem 2.2.2

**Comment by wwayne** [comment]
Thanks for fixing, but looks I still get problem:
```
Building native extensions.  This could take a while...
ERROR:  Error installing github_changelog_generator:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -rubygems /Library/Ruby/Gems/2.0.0/gems/rake-10.1.1/bin/rake RUBYARCHDIR=/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/github_changelog_generator-1.11.0 RUBYLIBDIR=/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/github_changelog_generator-1.11.0
fatal: Not a git repository (or any of the parent directories): .git
Running RuboCop...
Inspecting 24 files
........................

24 files inspected, no offenses detected
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.4.1/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.4.3/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.4.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.0/spec/spec_helper.rb:26:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 38700
....skywinder/ActionSheetPicker-3.0
.skywinder/ActionSheetPicker-3.0
.skywinder/ActionSheetPicker-3.0
.skywinder/ActionSheetPicker-3.0
.blah
Can't detect user and name from first parameter: 'blah' -> exit'
.....skywinder/ActionSheetPicker-3.0
.skywinder/ActionSheetPicker-3.0
...Detected user:skywinder, project:ActionSheetPicker-3.0
.Detected user:skywinder, project:ActionSheetPicker-3.0
.Detected user:skywinder, project:ActionSheetPicker-3.0
.Detected user:skywinder, project:ActionSheetPicker-3.0
.Detected user:skywinder, project:ActionSheetPicker-3.0
.Detected user:skywinder, project:ActionSheetPicker-3.0
.Detected user:skywinder, project:ActionSheetPicker-3.0
.Detected user:skywinder, project:ActionSheetPicker-3.0
.*............................./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
..../Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
..../Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
./Library/Ruby/Gems/2.0.0/gems/colorize-0.7.7/lib/colorize/class_methods.rb:9: warning: instance variable @disable_colorization not initialized
...F

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) GitHubChangelogGenerator::Reader example CHANGELOG files angular.js.md should eq 134
     # Implement heading_level for parser.
     Failure/Error: expect(subject.count).to eq(134)

       expected: 134
            got: 313

       (compared using ==)
     # ./spec/unit/reader_spec.rb:89:in `block (4 levels) in <top (required)>'

Failures:

  1) GitHubChangelogGenerator::Fetcher#github_fetch_tags when wrong token provided should raise Unauthorized error
     Failure/Error: options[:token] = INVALID_TOKEN

     RuntimeError:
       can't modify frozen Hash
     # ./spec/unit/fetcher_spec.rb:9:in `[]='
     # ./spec/unit/fetcher_spec.rb:9:in `options_with_invalid_token'
     # ./spec/unit/fetcher_spec.rb:51:in `block (4 levels) in <top (required)>'

Finished in 0.2175 seconds (files took 0.79132 seconds to load)
103 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/unit/fetcher_spec.rb:54 # GitHubChangelogGenerator::Fetcher#github_fetch_tags when wrong token provided should raise Unauthorized error

Randomized with seed 38700

[Coveralls] Outside the CI environment, not sending data.
Coverage report generated for RSpec to /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.0/coverage. 593 / 1069 LOC (55.47%) covered.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.4.1/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.4.3/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.4.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

rake failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/github_changelog_generator-1.11.0/gem_make.out
```
* Ruby: 2.0.0
* Gem: 2.5.2

**Comment by skywinder** [comment]
@wwayne thanks for mention. I try to fix it. More info here: #329

**Comment by wwayne** [comment]
I install latest 1.10.4, but the `detect_since_tag` bug still there:
```
Found 13 tags
/Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.4/lib/github_changelog_generator/generator/generator_tags.rb:61:in `detect_since_tag': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.4/lib/github_changelog_generator/generator/generator_tags.rb:79:in `filter_since_tag'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.4/lib/github_changelog_generator/generator/generator_tags.rb:70:in `get_filtered_tags'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.4/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.4/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.4/lib/github_changelog_generator.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.10.4/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/local/bin/github_changelog_generator:22:in `load'
	from /usr/local/bin/github_changelog_generator:22:in `<main>'
```
Anyway, thanks for your hard word on this, this is not urgent for me, I can use this tool when you have time to fix the bug.

**Comment by skywinder** [comment]
@wwayne please kindly check `1.11.1`. Hope it works now

**Comment by wwayne** [comment]
Thanks, but it looks still not woking
```
Found 13 tags
/Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.1/lib/github_changelog_generator/generator/generator_tags.rb:61:in `detect_since_tag': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.1/lib/github_changelog_generator/generator/generator_tags.rb:79:in `filter_since_tag'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.1/lib/github_changelog_generator/generator/generator_tags.rb:70:in `get_filtered_tags'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.1/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.1/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.1/lib/github_changelog_generator.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.1/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/local/bin/github_changelog_generator:22:in `load'
	from /usr/local/bin/github_changelog_generator:22:in `<main>'
```
