### ISSUE TITLE
Cannot install gem

### ISSUE THREAD

**Issue by Hout** [skywinder/github-changelog-generator#335]
Somehow the installation fails:

```bash
$ gem install github_changelog_generator --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=github_changelog_generator
200 OK
GET https://api.rubygems.org/quick/Marshal.4.8/github_changelog_generator-1.11.0.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/github_changelog_generator-1.11.0.gemspec.rz
404 Not Found
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/github_changelog_generator-1.11.0.gemspec.rz)
```

Ruby is v2.2.0.

**Comment by olleolleolle** [comment]
1.11.0 was released, then yanked. Does gem update do anything?

**Comment by Hout** [comment]
Did that, no effect.
Installed v2.3.0 with rbenv, interesting!
```bash
$ gem install github_changelog_generator --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=github_changelog_generator
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/github_changelog_generator-1.11.0.gemspec.rz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/github_changelog_generator-1.11.0.gemspec.rz
404 Not Found
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/github_changelog_generator-1.11.0.gemspec.rz)
```
What is that: `DNS result has no information for _rubygems._tcp.api.rubygems.org`? Something wrong with my ruby after all?

**Comment by olleolleolle** [comment]
A new release may be the only viable fix - forward is the way ahead.

**Comment by Hout** [comment]
Ok I will sit still in awaiting expectance. 
Thamks for your efforts so far and for a nice tool!

**Comment by skywinder** [comment]
@Hout please, try now.

**Comment by Hout** [comment]
It is different now:

```
$ gem install github_changelog_generator
Building native extensions.  This could take a while...
ERROR:  Error installing github_changelog_generator:
	ERROR: Failed to build gem native extension.

    /Users/jeroen/.rbenv/versions/2.2.0/bin/ruby -rubygems /Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/Users/jeroen/.rbenv/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/github_changelog_generator-1.11.1 RUBYLIBDIR=/Users/jeroen/.rbenv/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/github_changelog_generator-1.11.1
fatal: Not a git repository (or any of the parent directories): .git
Running RuboCop...
Inspecting 25 files
.........................

25 files inspected, no offenses detected
/Users/jeroen/.rbenv/versions/2.2.0/bin/ruby -I/Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib:/Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.3/lib /Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- codeclimate-test-reporter (LoadError)
	from /Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/github_changelog_generator-1.11.1/spec/spec_helper.rb:18:in `<top (required)>'
	from /Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration.rb:1295:in `each'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration.rb:1295:in `requires='
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration_options.rb:108:in `each'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/runner.rb:105:in `setup'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/runner.rb:92:in `run'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/runner.rb:78:in `run'
	from /Users/jeroen/.rbenv/gems/2.2.0/gems/rspec-core-3.4.3/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.3/exe/rspec:4:in `<main>'
/Users/jeroen/.rbenv/versions/2.2.0/bin/ruby -I/Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib:/Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.3/lib /Users/jeroen/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

rake failed, exit code 1

Gem files will remain installed in /Users/jeroen/.rbenv/gems/2.2.0/gems/github_changelog_generator-1.11.1 for inspection.
Results logged to /Users/jeroen/.rbenv/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/github_changelog_generator-1.11.1/gem_make.out
```

**Comment by olleolleolle** [comment]
The default task should perhaps only be "make the manual", not "run the tests and make the manual".

https://github.com/skywinder/github-changelog-generator/blob/master/Rakefile#L23

**Comment by skywinder** [comment]
@olleolleolle 
I agree with it. But reason, why I leave it - because before 341fb109ab it was 

    task default: [:rubocop, :rspec]

And works fine..Any ideas, what happens now? Why it stop works?

**Comment by olleolleolle** [comment]
@skywinder Because the change that changed things was gemspec's `extensions` (a list which lists paths which is run as code upon `gem install` having placed all Ruby files in place) now include only `Rakefile`, which has these imports that we now support. 

The `rspec` sub-task starts RSpec, which requires `spec_helper` which inlcudes these current problematic things.

**Comment by Hout** [comment]
Not being hindered by any knowledge of gems: it must have something to do with 
```
Not a git repository (or any of the parent directories): .git
``` 
when it tries to build the native extension.

**Comment by skywinder** [comment]
@olleolleolle #337 is right solution in that case?

**Comment by olleolleolle** [comment]
@skywinder I believe so. Perhaps you want to change the CI invocations later - perhaps with a specific CI rake task that does the necessary things.

**Comment by skywinder** [comment]
@olleolleolle [circleci](https://circleci.com/gh/skywinder/github-changelog-generator/336#build-timing) runs `bundle exec rspec --color --require spec_helper spec --format progress`

And [Travis](https://travis-ci.org/skywinder/github-changelog-generator/builds/111745497)
`bundle exec rake checks` according `.travis.yml` file. So everything is fine! :wink:

**Comment by Hout** [comment]
Success! Thanks for the quick resolution guys! :+1:

**Comment by olleolleolle** [comment]
@Hout Shoutout to the caring community that tests stuff out!
