### ISSUE TITLE
Feature Request: On using a public token on a private repo and getting a 404, fail informatively

### ISSUE THREAD

**Issue by olleolleolle** [skywinder/github-changelog-generator#367]
When having mis-configured github-changelog-generator, with a token with the wrong permissions (it needs `repos` to work), the error output is:

```
/Users/totoro/.rvm/gems/ruby-2.3.0/gems/github_api-0.13.1/lib/github_api/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/repos/mysecret/private-repo/tags: 404 Not Found (Github::Error::NotFound)
    from /Users/totoro/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
    from /Users/totoro/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
    from /Users/totoro/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /Users/totoro/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /Users/totoro/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /Users/totoro/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /Users/totoro/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
```

This 404 from the GitHub API is an error which stops execution, and we could present a more informative error message, which speculated on possible causes and showed a link to the docs on making a token with private repo permissions.

**Comment by alexdotgit** [comment]
First timer here! Would really love to try and tackle this issue if I'm able to @olleolleolle

**Comment by olleolleolle** [comment]
Go ahead, make a test, make a PR, it's open!

**Comment by deohtee** [comment]
Hey @olleolleolle , is this still an issue even with the OctoKit gem? Or did the error change similar to #525 ?

**Comment by olleolleolle** [comment]
The errors from Octokit are good and fail with mention of the API, which helps guide the user. 

But, the specific thing, the token privilege group `repos` being needed to have access to private repositories, that detail is not in the octokit message.

**Comment by olleolleolle** [comment]
I should change the description field to reflect that that is what we need, if anything.

**Comment by deohtee** [comment]
Hey @olleolleolle, really excited to get started. I've been trying to familiarize myself with the code  here and have been trying to pin down where to start. 

Just want to double check, but would this be a good starting place for this issue? https://github.com/skywinder/github-changelog-generator/blob/master/lib/github_changelog_generator/octo_fetcher.rb#L314-L317 

Thank you for the guidance 😄

**Comment by olleolleolle** [comment]
I believe this would be a great place to have more information. 

Whether the longer explanation is presented directly there, in a man page or at a URL is a matter of refining. 

Getting the basic tip into that abort string would help.

**Comment by olleolleolle** [comment]
I have updated the Description of the Issue with the new backtrace and error raised.

**Comment by olleolleolle** [comment]
Example output that I'm thinking of would be usable by someone trying to get this to work:

> The \<username>/\<project> repository was not found. Does it exist? If private, did your token have the "repos" permission?
