### ISSUE TITLE
GHE not working with --github-site set to an enterprise site

### ISSUE THREAD

**Issue by cormacmccarthy** [skywinder/github-changelog-generator#395]
I'm able to successfully use the tool to create a changelog for a site on github proper, but, when I try and run it against my enterprise site, it doesn't work.

```
$ github_changelog_generator --no-author --unreleased-only --compare-link --github-site=https://github.mycorporateGHE.com --token=$CHANGELOG_GE_TOKEN
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :base=>"HISTORY.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>false,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :git_remote=>"origin",
 :unreleased_only=>true,
 :github_site=>"https://github.mycorporateGHE.com",
 :token=>"hidden value",
 :user=>"cormacmccarthy",
 :project=>"my-project"}

/Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/fetcher.rb:55:in `rescue in check_github_response': undefined method `body' for #<Github::Error::Unauthorized:0x007fc24a1f00b8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/fetcher.rb:52:in `check_github_response'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/fetcher.rb:46:in `get_all_tags'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator.rb:29:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.13.0/bin/github_changelog_generator:4:in `<top (required)>'
	from /usr/local/bin/github_changelog_generator:23:in `load'
	from /usr/local/bin/github_changelog_generator:23:in `<main>'
```

**Comment by olleolleolle** [comment]
Hello, thanks for registering this!

I don't have access to a GHE, and am guessing a little here, to try and diagnose what's wrong.

Have you tried _also_ adding the option `--github-api` to the above invocation?

```
        opts.on("--github-api [URL]", "The enterprise endpoint to use for your Github API.") do |last|
```

**Comment by cormacmccarthy** [comment]
I believe that did the trick! Well, at least, I didn't get an error. I got:

```
Found 2 tags
Fetching tags dates: 2/2
Sorting tags...
Received issues: 0
Fetching merged dates: 0
Filtered pull requests: 0
Filtered issues: 0
Fetching events for issues and PR: 0
Fetching closed dates for issues: Done!
Done!
```

So, it's an empty CHANGELOG, but, I'm assuming that's related to other things that I can easily fix, and unrelated to GHE issues. Thanks!

**Comment by olleolleolle** [comment]
@cormacmccarthy If you were to read about this, say, in the docs. Where would you want to learn this?

**Comment by olleolleolle** [comment]
@cormacmccarthy I'm asking because I think you and I can make an edit to the README together.
