### ISSUE TITLE
Broken multi hyphen options in param file

### ISSUE THREAD

**Issue by thorsteneckel** [skywinder/github-changelog-generator#440]
Hi there,

currently it seems not possible to use options that contain multiple hyphens in the param file like e.g. `issue-line-labels`. This causes the following error:

```
/Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/lib/github_changelog_generator/parser_file.rb:51:in `rescue in parse_line!': Failed on line #8: "issue-line-labels=enhancement,feature,bug,minor bug,security" (GitHubChangelogGenerator::ParserError)
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/lib/github_changelog_generator/parser_file.rb:47:in `parse_line!'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/lib/github_changelog_generator/parser_file.rb:33:in `block in parse!'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/lib/github_changelog_generator/parser_file.rb:33:in `each'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/lib/github_changelog_generator/parser_file.rb:33:in `each_with_index'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/lib/github_changelog_generator/parser_file.rb:33:in `parse!'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/lib/github_changelog_generator/parser.rb:13:in `parse_options'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/lib/github_changelog_generator.rb:27:in `initialize'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/bin/github_changelog_generator:5:in `new'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.13.2/bin/github_changelog_generator:5:in `<top (required)>'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/bin/github_changelog_generator:22:in `load'
  from /Users/thorsteneckel/.rvm/gems/ruby-2.3.1/bin/github_changelog_generator:22:in `<main>'
```

**Comment by olleolleolle** [comment]
Thanks for fixing this!
