### ISSUE TITLE
Error: can't convert Sawyer::Resource to Array when iterating over a 301 Moved Permanently

### ISSUE THREAD

**Issue by Turbo87** [skywinder/github-changelog-generator#448]
when trying to run this generator I'm hitting the following error:

```
/Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/octo_fetcher.rb:101:in `concat': can't convert Sawyer::Resource to Array (Sawyer::Resource#to_ary gives NilClass) (TypeError)
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/octo_fetcher.rb:101:in `block in github_fetch_tags'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/octo_fetcher.rb:269:in `iterate_pages'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/octo_fetcher.rb:98:in `github_fetch_tags'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/octo_fetcher.rb:69:in `block in get_all_tags'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/octo_fetcher.rb:286:in `block in check_github_response'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/octo_fetcher.rb:285:in `check_github_response'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/octo_fetcher.rb:69:in `get_all_tags'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/generator/generator_tags.rb:9:in `fetch_and_filter_tags'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator/generator/generator_generation.rb:8:in `compound_changelog'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/lib/github_changelog_generator.rb:34:in `run'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/gems/github_changelog_generator-1.14.1/bin/github_changelog_generator:5:in `<top (required)>'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/bin/github_changelog_generator:23:in `load'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/bin/github_changelog_generator:23:in `<main>'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tbn/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

I've tried it with several other Ruby versions, uninstalled and reinstalled the gen again, but nothing works... any clue what I'm doing wrong?

**Comment by olleolleolle** [comment]
Thanks for this report, @Turbo87. Let's figure it out!

**Comment by Turbo87** [comment]
thanks to @rwjblue we've figured it out: this was caused by an outdated `.github_changelog_generator` file. the repository was recently moved to another organization but the file wasn't updated. while this was not a real issue of the generator, the error message could be improved though to tell you that the repository wasn't found.

**Comment by olleolleolle** [comment]
@Turbo87 Thanks for figuring it out!

**Comment by olleolleolle** [comment]
@Turbo87 To improve chances of us fixing your issue, do you have a before/after of the `.github_changelog_generator` file?

**Comment by Turbo87** [comment]
@olleolleolle see https://github.com/ember-cli/ember-cli-mocha/commit/d712d0968485c03118ebb8517c282a372919013d

**Comment by olleolleolle** [comment]
I have a hard time reproducing this failure. Things I tried:

- pointing it at olleolleolle/github-changelog-generator
- pointing it at olleolleolle/olleolleolle.github.io which has 0 tags (does not fail)

Hm. Hm. Is it about having transferred ownership of the repo?

**Comment by olleolleolle** [comment]
Now! Now I can.

Using the original ember-cli-mocha one!

**Comment by Turbo87** [comment]
> Is it about having transferred ownership of the repo?

It might be. I know that GitHub is redirecting *some* stuff, but maybe not everything.
