### ISSUE TITLE
v1.14.0 Fails with missing /tmp/ path on Windows

### ISSUE THREAD

**Issue by Arcanemagus** [skywinder/github-changelog-generator#458]
It seems that v1.14.0 introduced a bug where it attempts to create `/tmp/github_changelog-logger.log`... which isn't a valid path on Windows and thus fails.

The stack trace:

```text
C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:702:in `open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:635:in `initialize'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `new'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/lib/github_changelog_generator/octo_fetcher.rb:51:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/lib/github_changelog_generator/octo_fetcher.rb:51:in `init_cache'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/lib/github_changelog_generator/octo_fetcher.rb:34:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/lib/github_changelog_generator/generator/generator.rb:24:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/lib/github_changelog_generator/generator/generator.rb:24:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/lib/github_changelog_generator.rb:28:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/lib/github_changelog_generator.rb:28:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/bin/github_changelog_generator:5:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.0/bin/github_changelog_generator:5:in `<top (required)>'
        from C:/Ruby23-x64/bin/github_changelog_generator:22:in `load'
        from C:/Ruby23-x64/bin/github_changelog_generator:22:in `<main>'
```

It's possible this is related to https://github.com/skywinder/github-changelog-generator/commit/41271b1ecbd0161ad45c0b48304c8e38fc6c72e0, but I'm just guessing here.

Side note: An AppVeyor config was added back in https://github.com/skywinder/github-changelog-generator/pull/350, but it doesn't seem to currently be being built?

If there is any further information needed, or any debug steps you want me to take don't hesitate to ask!

**Comment by vatbub** [comment]
Guys, me too, the stacktrace is 
```
C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:702:in `open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:635:in `initialize'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `new'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `init_cache'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:34:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `<top (required)>'
        from C:/Ruby23-x64/bin/github_changelog_generator:22:in `load'
        from C:/Ruby23-x64/bin/github_changelog_generator:22:in `<main>'
```

**Comment by Arcanemagus** [comment]
Ah, looks like the discussion in #459 never got migrated over here.

The short story is this is fixed by the changes in #459, however the certificate store bundled with Ruby on Windows is too out of date to authenticate the SSL from GitHub, so it fails anyway. @olleolleolle was looking into a solution to this per https://github.com/skywinder/github-changelog-generator/pull/459#issuecomment-265009731.

**Comment by nnn** [comment]
Getting same thing as @vatbub. Are there any existing solutions for this now?

**Comment by olleolleolle** [comment]
A workaround to try could be:

Setting the options `cache_file` and `cache_log` can be set, to avoid running the above code:

https://github.com/skywinder/github-changelog-generator/blob/master/lib/github_changelog_generator/octo_fetcher.rb#L34-L35

**Comment by Arcanemagus** [comment]
Marking this as closed since #459 fixes the issue described here. Please follow #475 for the next issue preventing this from running on Windows.

If you don't need the latest version you can force the v1.13.2 version as it is the last working version on Windows.

**Comment by ceddlyburge** [comment]
I just gem installed this on a windows machine and hit the same error.

I couldn't find out how to set --cache_log and --cache-file to nil via command line parameters.

I was able to make it work by simply creating a c:\tmp folder though.

**Comment by radarsh** [comment]
Git bash user on Windows. I solved it by adding `--cache_log /dev/null` command line argument.

**Comment by RareScrap** [comment]
@ceddlyburge Thank you!

**Comment by LexiconCode** [comment]
> I was able to make it work by simply creating a c:\tmp folder though.

This should be included on the readme for windows

**Comment by olleolleolle** [comment]
@LexiconCode I added a link to  this Issue, and the shortest-possible Workaround note in the FAQ. Would you've found it?
