### ISSUE TITLE
Critical logging error

### ISSUE THREAD

**Issue by SplittyDev** [skywinder/github-changelog-generator#481]
Hey, when trying to run this on Windows I'm getting the following error:
```
C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:702:in `open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:635:in `initialize'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `new'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `initialize'
```

Apparently it's trying to create a logfile in a directory that doesn't exist.

**Comment by olleolleolle** [comment]
@SplittyDev https://github.com/skywinder/github-changelog-generator/issues/458 this is the same issue, right?

**Comment by SplittyDev** [comment]
@olleolleolle Oh yeah, sorry I didn't see that.
