### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Lord-Haji** [skywinder/github-changelog-generator#510]
```
E:\NecroBot>  github_changelog_generator
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :base=>"HISTORY.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :issue_line_labels=>[],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :git_remote=>"origin",
 :http_cache=>true,
 :cache_file=>"/tmp/github-changelog-http-cache",
 :cache_log=>"/tmp/github-changelog-logger.log",
 :user=>"Necrobot-Private",
 :project=>"NecroBot",
 :token=>nil}

C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:702:in `open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:635:in `initialize'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `new'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `init_cache'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:34:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `<top (required)>'
        from C:/Ruby23-x64/bin/github_changelog_generator:22:in `load'
        from C:/Ruby23-x64/bin/github_changelog_generator:22:in `<main>'

E:\NecroBot>git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
```

**Comment by Lord-Haji** [comment]
Nothing happens after this

**Comment by olleolleolle** [comment]
This issue is fixed in master branch and will be out in the next release.

**Comment by olleolleolle** [comment]
Thank you for reporting!
