### ISSUE TITLE
Error in generating changelog on Windows

### ISSUE THREAD

**Issue by tzejohn** [skywinder/github-changelog-generator#521]
I am seeing the following error when running the generator. This is run on a windows box, against a repo in an internal GitHub Enterprise installation. Any idea on how to troubleshoot further?

```
D:\projects\ws\auth.service>github_changelog_generator --github-site https://pig.abbvienet.com --github-api https://pig.abbvienet.com/api/v3 --token XXXXXXXXXXXXXXXXXXXXXXX
D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/parser.rb:250:in ``': No such file or directory -
git config --get remote.origin.url (Errno::ENOENT)
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/parser.rb:250:in `user_and_project_from_git'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/parser.rb:233:in `fetch_user_and_project'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/parser.rb:18:in `parse_options'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:27:in `initialize'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `new'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `<top (required)>'
        from D:/tools/Ruby23-x64/bin/github_changelog_generator:22:in `load'
        from D:/tools/Ruby23-x64/bin/github_changelog_generator:22:in `<main>'
```

**Comment by olleolleolle** [comment]
@tzejohn Is there a Git installation in the path?

Can you use `-p projectname` and `-u username` to try not using the code which has this issue (it is trying to find projectname and username using git metadata)/

**Comment by tzejohn** [comment]
Sorry. I was troubleshooting when running under the bash windows prompt and under the windows command prompt. I thought the error was the same, but it was not. Here is the error trace when running under bash on windows. it seems it cannot create the log file, but I can use ~touch~ from the shell and create the file at the same path.

```
tangtj@GPRULCD915720  /d/projects/ws/auth.service
$ github_changelog_generator --github-site https://pig.abbvienet.com --github-a
pi https://pig.abbvienet.com/api/v3 --token XXXXXXXXXXXXXXXXXXXXX

Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :base=>"HISTORY.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :issue_line_labels=>[],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :git_remote=>"origin",
 :http_cache=>true,
 :cache_file=>"/tmp/github-changelog-http-cache",
 :cache_log=>"/tmp/github-changelog-logger.log",
 :github_site=>"https://pig.abbvienet.com",
 :github_endpoint=>"https://pig.abbvienet.com/api/v3",
 :token=>"hidden value",
 :user=>"PIKM",
 :project=>"auth.service"}

D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)
        from D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `open'
        from D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
        from D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
        from D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:702:in `open_logfile'
        from D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
        from D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:635:in `initialize'
        from D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `new'
        from D:/tools/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `initialize'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `new'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `init_cache'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:34:in `initialize'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `new'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `initialize'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `new'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `initialize'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `new'
        from D:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `<top (required)>'
        from D:/tools/Ruby23-x64/bin/github_changelog_generator:22:in `load'
        from D:/tools/Ruby23-x64/bin/github_changelog_generator:22:in `<main>'
```

**Comment by olleolleolle** [comment]
Oh? Then you have the issue which has plagued Windows users of that version - either downgrade or use master. 

If you search for `specific_install` in Issues, you may find a way to use latest, today.

**Comment by olleolleolle** [comment]
This problem has been solved in the master branch. Closing this issue.
