### ISSUE TITLE
Markdown: add a newline before the Full Changelog links

### ISSUE THREAD

**Issue by olleolleolle** [skywinder/github-changelog-generator#546]
Formatting suggestion: add a newline between "## <version>" and the "Full Changelog" links -- some markdown parsers don't like things immediately after headers.

**Comment by ianroberts131** [comment]
Ok if I take a stab at this? Looking to get started with open source development.

**Comment by olleolleolle** [comment]
@ianroberts131 Go ahead!

**Comment by ianroberts131** [comment]
I \*think\* I've located where the change should be made, so decided to try to throw a string there and test to see if I was on the right track...but I'm having trouble figuring out how to test it.

I believe the change needs to be made in `generator_generation.rb`, Line 69.
Here was how I planned to test this:
```ruby
log += if newer_tag_name.equal?(options[:unreleased_label])
         "## [#{newer_tag_name}](#{release_url})\n\n"
       else
         "## [#{newer_tag_name}](#{release_url}) (#{time_string})\n HELLLOOOOOOOO"
       end
```
I think I just need to insert another `\n`, but wasn't sure this would be visible to me so figured I'd try something that would be very obvious.

You can see the code here: https://github.com/ianroberts131/github-changelog-generator/blob/add-newline-after-version/lib/github_changelog_generator/generator/generator_generation.rb

In order to test the code, I've tried a couple of things:
1. Fork the changlog_test repository and create a Gemfile that references my forked version of github-changelog-generator
2. Create my own test repository, and then run the `github_changelog_generator` command locally.

Each time I run the command, I get the following output, but nothing happens:
```ruby
C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:702:in `open_logfile'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:635:in `initialize'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `new'
        from C:/Ruby23-x64/lib/ruby/2.3.0/logger.rb:353:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `init_cache'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:34:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `initialize'
        from C:/Users/Ian/bloc/open-source/github-changelog-generator/lib/github_changelog_generator.rb:29:in `new'
        from C:/Users/Ian/bloc/open-source/github-changelog-generator/lib/github_changelog_generator.rb:29:in `initialize'
        from C:/Users/Ian/bloc/open-source/github-changelog-generator/bin/github_changelog_generator:5:in `new'
        from C:/Users/Ian/bloc/open-source/github-changelog-generator/bin/github_changelog_generator:5:in `<main>'
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :base=>"HISTORY.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :issue_line_labels=>[],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :git_remote=>"origin",
 :http_cache=>true,
 :cache_file=>"/tmp/github-changelog-http-cache",
 :cache_log=>"/tmp/github-changelog-logger.log",
 :user=>"ianroberts131",
 :project=>"Test",
 :token=>nil}
```

I'm unsure if those errors are part of the problem, but it seems like the command runs in the end and the `.MD` file should be created.

Any help would be greatly appreciated. Thanks!

**Comment by olleolleolle** [comment]
Maybe you only need to run the CLI command wrapped in `bundle exec`, it seems that there are other pieces of code being run - code from outside what you have in the Gemfile.

**Comment by olleolleolle** [comment]
Bundler manipulates your Ruby $LOAD_PATH to place your Gemfile-selected code first on it.

**Comment by olleolleolle** [comment]
Hope this helps!

**Comment by 3minus1** [comment]
I have added HR breaks between each chanege_log for improved readability. I've created a pull request. My first open source contribution. Would love some comments.

**Comment by olleolleolle** [comment]
@ianroberts131 Thanks for your efforts in this!

Would you like to go ahead with the change, or leave it to someone else, or are you wondering something?
