### ISSUE TITLE
please write somewhere in the docs that a 'tmp' folder has to exist in C:/ for windows

### ISSUE THREAD

**Issue by onqtam** [skywinder/github-changelog-generator#585]

**Comment by h3xstream** [comment]
@onqtam is probably refering to hardcoded path that refer to unix specific `/tmp` folder.

## Stacktrace
```
C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:752:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:752:in `open'
        from C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:752:in `create_logfile'
        from C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:746:in `rescue in open_logfile'
        from C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:743:in `open_logfile'
        from C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:736:in `set_dev'
        from C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:671:in `initialize'
        from C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:387:in `new'
        from C:/Ruby24-x64/lib/ruby/2.4.0/logger.rb:387:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `init_cache'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:34:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `<top (required)>'
        from C:/Ruby24-x64/bin/github_changelog_generator:23:in `load'
        from C:/Ruby24-x64/bin/github_changelog_generator:23:in `<main>'
```

## Workaround

Create a folder `C:/tmp/`

**Comment by h3xstream** [comment]
Location of the bug : 

https://github.com/skywinder/github-changelog-generator/blob/1dc33e3005ef682ce9be459196c9c51a2c17c24e/lib/github_changelog_generator/parser.rb#L221-L224

**Comment by 304NotModified** [comment]
even with a c:/tmp I get the same error (Windows 10 x64)

> C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:754:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)

All users has write access tot c:/tmp

**Comment by weitony111** [comment]
@304NotModified Please try to create the `tmp` directory under your current working directory or root folder of your current drive.

**Comment by NillerMedDild** [comment]
Thank you for opening this issue in the first place, it was a very quick fix thanks to this :)
